export const FETCH_COURSE_DETAIL = "FETCH_COURSE_DETAIL";
export const FETCH_COURSES = "FETCH_COURSES";

export const FETCH_COURSES_CATALOG = "FETCH_COURSES_CATALOG";
export const FETCH_COURSES_DETAIL = "FETCH_COURSES_DETAIL";

export const ADD_COURSE = "ADD_COURSE";
export const DELETE_COURSE = "DELETE_COURSE";
export const FETCH_COURSE_PAGINATION = "FETCH_COURSE_PAGINATION";
export const PAYMENT = "PAYMENT"

export const LOGIN = "LOGIN";
export const SIGNUP = "SIGNUP";
export const SET_CURRENT_USER = "SET_CURRENT_USER"
export const UPDATE_COURSE = "UPDATE_COURSE"
export const EDIT_COURSE = "EDIT_COURSE"
export const ADD_USER = "ADD_USER";
export const SEARCH_USER = "SEARCH_USER";
export const EDIT_USER = "EDIT_USER"
export const UPDATE_USER = "UPDATE_USER"
export const DELETE_USER = "DELETE_USER";
export const FETCH_USER = "FETCH_USER";
export const SEARCH_COURSES = "SEARCH_COURSES";
export const ADD_TO_CART = "ADD_TO_CART";
export const DELETE_CART = "DELETE_CART";
export const SORT_PRICE_HIGH_TO_LOW = "SORT_PRICE_HIGH_TO_LOW";
export const SORT_PRICE_LOW_TO_HIGH = "SORT_PRICE_LOW_TO_HIGH";

export const SORT_NAME_LOW_TO_HIGH = "SORT_NAME_LOW_TO_HIGH";
export const SORT_NAME_HIGH_TO_LOW = "SORT_NAME_HIGH_TO_LOW";

export const ADD_COURSE_FAVORIES = "ADD_COURSE_FAVORIES";
export const DELETE_COURSE_FAVORIES = "DELETE_COURSE_FAVORIES";
